kind: Namespace
apiVersion: v1
metadata:
  name: face-validator
  labels:
    name: face-validator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: face-validator-frontend
  namespace: face-validator
spec:
  selector:
    matchLabels:
      app: face-validator-frontend
  template:
    metadata:
      labels:
        app: face-validator-frontend
    spec:
      containers:
      - name: frontend
        image: cr.suaihack.ru/face-validator-frontend:1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: face-validator-frontend-service
  namespace: face-validator
spec:
  selector:
    app: face-validator-frontend
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: face-validator-ingress
  namespace: face-validator
  labels:
    name: face-validator-ingress
  annotations:
    cert-manager.io/cluster-issuer: lets-encrypt
spec:
  tls:
  - hosts:
    - face-validator.suaihack.ru
    secretName: face-validator-ingress-tls
  rules:
  - host: face-validator.suaihack.ru
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: face-validator-frontend-service
            port: 
              number: 80